// ===================================================================
// Amalgamated Header (Auto-generated by scripts/amalgamate.py)
// ===================================================================
#pragma once

#include <array>
#include <climits>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <deque>
#include <limits>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

// --- BEGIN FILE: tables.hpp ---

namespace nthash::internal {

// 64-bit random seeds corresponding to bases and their complements
constexpr uint64_t SEED_A = 0x3eb13b9046685257;
constexpr uint64_t SEED_C = 0x22310aefe5d92bca;
constexpr uint64_t SEED_G = 0x83677b6b400f4886;
constexpr uint64_t SEED_T = 0x9fe74a14e3be311b;
constexpr uint64_t SEED_N = 0x0000000000000000;

// offset for the complement base in the random seeds table
constexpr uint8_t CP_OFF = 0x07;

constexpr int ASCII_SIZE = 256;

[[nodiscard]] constexpr std::array<uint64_t, ASCII_SIZE>
generate_seed_table() noexcept
{
  std::array<uint64_t, ASCII_SIZE> tab{};
  tab['A'] = tab['a'] = SEED_A;
  tab['C'] = tab['c'] = SEED_C;
  tab['G'] = tab['g'] = SEED_G;
  tab['T'] = tab['t'] = tab['U'] = tab['u'] = SEED_T;
  tab['A' & CP_OFF] = SEED_T;
  tab['C' & CP_OFF] = SEED_G;
  tab['T' & CP_OFF] = SEED_A;
  tab['U' & CP_OFF] = SEED_A;
  tab['G' & CP_OFF] = SEED_C;
  return tab;
}

[[nodiscard]] constexpr std::array<uint8_t, ASCII_SIZE>
generate_convert_table() noexcept
{
  std::array<uint8_t, ASCII_SIZE> tab{};
  for (auto& val : tab) {
    val = 255;
  }
  tab['A'] = tab['a'] = 0;
  tab['C'] = tab['c'] = 1;
  tab['G'] = tab['g'] = 2;
  tab['T'] = tab['t'] = tab['U'] = tab['u'] = 3;
  return tab;
}

[[nodiscard]] constexpr std::array<uint8_t, ASCII_SIZE>
generate_rc_convert_table() noexcept
{
  std::array<uint8_t, ASCII_SIZE> tab{};
  for (auto& val : tab) {
    val = 255;
  }
  tab['A'] = tab['a'] = 3;
  tab['C'] = tab['c'] = 2;
  tab['G'] = tab['g'] = 1;
  tab['T'] = tab['t'] = tab['U'] = tab['u'] = 0;
  return tab;
}

alignas(64) inline constexpr auto SEED_TAB = generate_seed_table();
alignas(64) inline constexpr auto CONVERT_TAB = generate_convert_table();
alignas(64) inline constexpr auto RC_CONVERT_TAB = generate_rc_convert_table();

} // namespace nthash::internal

// --- END FILE: tables.hpp ---
// --- BEGIN FILE: utils.hpp ---

namespace nthash::internal {

using HASH_TYPE = uint64_t;
constexpr unsigned int HASH_BITS = sizeof(HASH_TYPE) * CHAR_BIT;

/**
 * This lets us minimize object size. Good for performance if it's
 * copied in, e.g., DBG traversal.
 */
using K_TYPE = uint16_t;

// number of rotations per roll
constexpr unsigned int ROT_R = 7;

// number of shifts per roll
constexpr unsigned int SHIFT_C = 27; // C has to be >= 22

// shift for generating multiple hash values
constexpr unsigned int MULTISHIFT = 27;

// seed for generating multiple hash values
constexpr HASH_TYPE MULTISEED = 0x90b45d39fb6da1fa;

[[nodiscard]] inline constexpr HASH_TYPE
canonical(const HASH_TYPE fwd, const HASH_TYPE rev) noexcept
{
  return fwd + rev;
}

[[nodiscard]] inline constexpr HASH_TYPE
rotl(HASH_TYPE x, unsigned int r) noexcept
{
  return (x << (r & (HASH_BITS - 1))) | (x >> ((-r) & (HASH_BITS - 1)));
}

[[nodiscard]] inline constexpr HASH_TYPE
rotr(HASH_TYPE x, unsigned int r) noexcept
{
  return (x >> (r & (HASH_BITS - 1))) | (x << ((-r) & (HASH_BITS - 1)));
}

/**
 * Steps the hash forward (to the right) by d positions.
 */
[[nodiscard]] inline constexpr HASH_TYPE
roll_next(HASH_TYPE hash_value) noexcept
{
  hash_value = rotl(hash_value, ROT_R);
  return hash_value ^ (hash_value << SHIFT_C);
}

[[nodiscard]] inline constexpr HASH_TYPE
roll_next(HASH_TYPE hash_value, unsigned d) noexcept
{
  for (unsigned i = 0; i < d; i++) {
    hash_value = roll_next(hash_value);
  }
  return hash_value;
}

/**
 * Steps the hash backward (to the left) by d positions.
 */
[[nodiscard]] inline constexpr HASH_TYPE
roll_back(HASH_TYPE hash_value) noexcept
{
  HASH_TYPE y = hash_value;
  for (unsigned s = SHIFT_C; s < HASH_BITS; s *= 2) {
    y ^= (y << s);
  }
  return rotr(y, ROT_R);
}

[[nodiscard]] inline constexpr HASH_TYPE
roll_back(HASH_TYPE hash_value, unsigned d) noexcept
{
  for (unsigned i = 0; i < d; i++) {
    hash_value = roll_back(hash_value);
  }
  return hash_value;
}

inline void
extend_hashes(HASH_TYPE fwd_hash,
              HASH_TYPE rev_hash,
              HASH_TYPE k_mult,
              std::vector<HASH_TYPE>& hash_array) noexcept
{
  HASH_TYPE t_val;
  const auto base_hash = canonical(fwd_hash, rev_hash);
  hash_array[0] = base_hash;
  for (unsigned i = 1; i < hash_array.size(); i++) {
    t_val = base_hash * (i ^ k_mult);
    t_val ^= t_val >> MULTISHIFT;
    hash_array[i] = t_val;
  }
}

/**
 * Extend hash array using a base hash value.
 * @param fwd_hash Forward hash value
 * @param rev_hash Reverse hash value
 * @param k k-mer size
 * @param h Size of the resulting hash array (number of extra hashes minus one)
 * @param h_val Array of size h for storing the output hashes
 */
inline void
extend_hashes(HASH_TYPE fwd_hash,
              HASH_TYPE rev_hash,
              K_TYPE k,
              std::vector<HASH_TYPE>& hash_array) noexcept
{
  const auto k_mult = static_cast<HASH_TYPE>(k) * MULTISEED;
  return extend_hashes(fwd_hash, rev_hash, k_mult, hash_array);
}

} // namespace nthash::internal

// --- END FILE: utils.hpp ---
// --- BEGIN FILE: internal.hpp ---

// --- END FILE: internal.hpp ---
// --- BEGIN FILE: utils.hpp ---

namespace nthash::kmer {

using internal::HASH_TYPE;
using internal::K_TYPE;

/**
 * Container for the two strand-specific forward-out and reverse-in masks.
 * Forward-out mask: k-th rotation of each base's seed.
 * Reverse-in mask: (k-1)-th rotation of each base's complement's seed.
 * Masks are cached for k, since k doesn't normally change in a single run.
 */
struct StrandMasks
{
  std::array<HASH_TYPE, 4> fwd_out{};
  std::array<HASH_TYPE, 4> rev_in{};

  constexpr StrandMasks() noexcept = default;

  StrandMasks(K_TYPE k)
  {
    static K_TYPE cached_k = 0;
    static std::array<HASH_TYPE, 4> cached_fwd;
    static std::array<HASH_TYPE, 4> cached_rev;
    if (k != cached_k) {
      constexpr std::array<HASH_TYPE, 4> seeds{
        internal::SEED_A, internal::SEED_C, internal::SEED_G, internal::SEED_T
      };
      for (size_t i = 0; i < seeds.size(); i++) {
        fwd_out[i] = internal::roll_next(seeds[i], k);
        rev_in[i] = internal::roll_next(seeds[seeds.size() - 1 - i], k - 1);
      }
      cached_fwd = fwd_out;
      cached_rev = rev_in;
      cached_k = k;
    } else {
      fwd_out = cached_fwd;
      rev_in = cached_rev;
    }
  }
};

/**
 * Generate the forward-strand hash value of the first k-mer in the sequence.
 * @param seq C array containing the sequence's characters
 * @param k k-mer size
 * @return Hash value of k-mer_0
 */
[[nodiscard]] inline constexpr HASH_TYPE
base_forward_hash(const char* seq, K_TYPE k) noexcept
{
  HASH_TYPE h_val = 0;
  for (K_TYPE i = 0; i < k; i++) {
    const auto index = static_cast<unsigned char>(seq[i]);
    h_val = internal::roll_next(h_val) ^ internal::SEED_TAB[index];
  }
  return h_val;
}

/**
 * Perform a roll operation on the forward strand.
 * @param fh_val Previous hash value computed for the sequence
 * @param out_mask Character mask to be removed (k-times roll of char_out)
 * @param char_in Character to be included
 * @return Rolled forward hash value
 */
[[nodiscard]] inline constexpr HASH_TYPE
next_forward_hash(HASH_TYPE fh_val,
                  HASH_TYPE out_mask,
                  unsigned char char_in) noexcept
{
  const auto in_mask = internal::SEED_TAB[char_in];
  return nthash::internal::roll_next(fh_val) ^ in_mask ^ out_mask;
}

/**
 * Perform a roll back operation on the forward strand.
 * @param fh_val Previous hash value computed for the sequence
 * @param char_out Character to be removed
 * @param in_mask Character mask to be included (k-th rotation of char_in)
 * @return Forward hash value rolled back
 */
[[nodiscard]] inline constexpr HASH_TYPE
prev_forward_hash(HASH_TYPE fh_val,
                  unsigned char char_out,
                  HASH_TYPE in_mask) noexcept
{
  const auto out_mask = internal::SEED_TAB[char_out];
  return nthash::internal::roll_back(fh_val ^ out_mask) ^ in_mask;
}

/**
 * Generate a hash value for the reverse-complement of the first k-mer in the
 * sequence.
 * @param seq C array containing the sequence's characters
 * @param k k-mer size
 * @return Hash value of the reverse-complement of k-mer_0
 */
[[nodiscard]] inline constexpr HASH_TYPE
base_reverse_hash(const char* seq, K_TYPE k) noexcept
{
  HASH_TYPE h_val = 0;
  for (K_TYPE i = 0; i < k; i++) {
    const auto index =
      static_cast<unsigned char>(seq[k - 1 - i]) & internal::CP_OFF;
    h_val = nthash::internal::roll_next(h_val) ^ internal::SEED_TAB[index];
  }
  return h_val;
}

/**
 * Perform a roll operation on the reverse-complement.
 * @param rh_val Previous reverse-complement hash value computed for the
 * sequence
 * @param char_out Character to be removed
 * @param in_mask Character mask to be included (k-th rotation of char_in)
 * @return Rolled hash value for the reverse-complement
 */
[[nodiscard]] inline constexpr HASH_TYPE
next_reverse_hash(HASH_TYPE rh_val,
                  unsigned char char_out,
                  HASH_TYPE in_mask) noexcept
{
  const auto out_mask = internal::SEED_TAB[char_out & internal::CP_OFF];
  return nthash::internal::roll_back(rh_val ^ out_mask) ^ in_mask;
}

/**
 * Perform a roll back operation on the reverse strand.
 * @param rh_val Previous hash value computed for the sequence
 * @param out_mask Character mask to be removed (k-times rotation of char_out)
 * @param char_in Character to be included
 * @return Reverse hash value rolled back
 */
[[nodiscard]] inline constexpr HASH_TYPE
prev_reverse_hash(HASH_TYPE rh_val,
                  HASH_TYPE out_mask,
                  unsigned char char_in) noexcept
{
  const auto in_mask = internal::SEED_TAB[char_in & internal::CP_OFF];
  return nthash::internal::roll_next(rh_val ^ out_mask) ^ in_mask;
}

inline HASH_TYPE
blind_fwd_out_mask(unsigned char c,
                   K_TYPE k,
                   const std::array<HASH_TYPE, 4>& fwd_out_mask)
{
  const auto loc = internal::CONVERT_TAB[c];
  return loc < 4 ? fwd_out_mask[loc]
                 : internal::roll_next(internal::SEED_TAB[c],
                                       static_cast<unsigned>(k));
}

inline HASH_TYPE
blind_rev_in_mask(unsigned char c,
                  K_TYPE k,
                  const std::array<HASH_TYPE, 4>& rev_in_mask)
{
  const auto loc = internal::CONVERT_TAB[c];
  return loc < 4 ? rev_in_mask[loc]
                 : internal::roll_next(internal::SEED_TAB[c & internal::CP_OFF],
                                       static_cast<unsigned>(k) - 1);
}

inline HASH_TYPE
blind_fwd_in_mask(unsigned char c,
                  K_TYPE k,
                  const std::array<HASH_TYPE, 4>& rev_in_mask)
{
  const auto loc = internal::CONVERT_TAB[c];
  return loc < 4 ? rev_in_mask[3 - loc]
                 : internal::roll_next(internal::SEED_TAB[c],
                                       static_cast<unsigned>(k) - 1);
}

inline HASH_TYPE
blind_rev_out_mask(unsigned char c,
                   K_TYPE k,
                   const std::array<HASH_TYPE, 4>& fwd_out_mask)
{
  const auto loc = internal::CONVERT_TAB[c];
  return loc < 4 ? fwd_out_mask[3 - loc]
                 : internal::roll_next(internal::SEED_TAB[c & internal::CP_OFF],
                                       static_cast<unsigned>(k));
}

} // namespace nthash::kmer

// --- END FILE: utils.hpp ---
// --- BEGIN FILE: blind.hpp ---

namespace nthash::kmer {

using internal::HASH_TYPE;
using internal::K_TYPE;

class BlindNtHash
{

public:
  /**
   * Construct an ntHash object for hashing k-mers on-the-fly.
   * @param seq C-string of the data. Only \p k characters will be used,
   * starting from \p pos.
   * @param hash_num Number of hashes to generate per k-mer
   * @param k K-mer size
   * @param pos Position in sequence to start hashing from
   */
  BlindNtHash(const char* seq, unsigned num_hashes, K_TYPE k, ssize_t pos = 0)
    : kmer(seq + pos, seq + pos + k)
    , pos(pos)
    , masks(k)
    , hash_arr(num_hashes)
  {
    if (k == 0) {
      throw std::invalid_argument("BlindNtHash: k must be greater than 0");
    }
    fwd_hash = kmer::base_forward_hash(seq + pos, k);
    rev_hash = kmer::base_reverse_hash(seq + pos, k);
    internal::extend_hashes(fwd_hash, rev_hash, k, hash_arr);
  }

  /**
   * Like the NtHash::roll() function, but instead of advancing in the
   * sequence BlindNtHash object was constructed on, the provided character
   * \p char_in is used as the next base. Useful if you want to query for
   * possible paths in an implicit de Bruijn graph graph.
   */
  void roll(char char_in)
  {
    const auto k = static_cast<K_TYPE>(kmer.size());
    const auto char_out_u = static_cast<unsigned char>(kmer.front());
    const auto char_in_u = static_cast<unsigned char>(char_in);
    const auto out_mask =
      kmer::blind_fwd_out_mask(char_out_u, k, masks.fwd_out);
    const auto in_mask = kmer::blind_rev_in_mask(char_in_u, k, masks.rev_in);

    fwd_hash = kmer::next_forward_hash(fwd_hash, out_mask, char_in_u);
    rev_hash = kmer::next_reverse_hash(rev_hash, char_out_u, in_mask);
    internal::extend_hashes(fwd_hash, rev_hash, k, hash_arr);
    kmer.erase(0, 1);
    kmer.push_back(char_in);
    ++pos;
  }

  /**
   * Like the roll(char char_in) function, but advance backwards.
   */
  void roll_back(char char_in)
  {
    const auto k = static_cast<K_TYPE>(kmer.size());
    const auto char_out_u = static_cast<unsigned char>(kmer.back());
    const auto char_in_u = static_cast<unsigned char>(char_in);
    const auto in_mask = kmer::blind_fwd_in_mask(char_in_u, k, masks.rev_in);
    const auto out_mask = kmer::blind_rev_in_mask(char_out_u, k, masks.rev_in);

    fwd_hash = kmer::prev_forward_hash(fwd_hash, char_out_u, in_mask);
    rev_hash = kmer::prev_reverse_hash(rev_hash, out_mask, char_in_u);
    internal::extend_hashes(fwd_hash, rev_hash, k, hash_arr);
    kmer.pop_back();
    kmer.insert(kmer.begin(), char_in);
    --pos;
  }

  /**
   * Like NtHash::peek(), but as if roll(char char_in) was called.
   */
  void peek(char char_in)
  {
    const auto k = static_cast<K_TYPE>(kmer.size());
    const auto char_out_u = static_cast<unsigned char>(kmer.front());
    const auto char_in_u = static_cast<unsigned char>(char_in);
    const auto out_mask =
      kmer::blind_fwd_out_mask(char_out_u, k, masks.fwd_out);
    const auto in_mask = kmer::blind_rev_in_mask(char_in_u, k, masks.rev_in);

    const auto fwd = kmer::next_forward_hash(fwd_hash, out_mask, char_in_u);
    const auto rev = kmer::next_reverse_hash(rev_hash, char_out_u, in_mask);
    internal::extend_hashes(fwd, rev, k, hash_arr);
  }

  /**
   * Like peek(char char_in), but as if roll_back(char char_in) was called.
   */
  void peek_back(char char_in)
  {
    const auto k = static_cast<K_TYPE>(kmer.size());
    const auto char_out_u = static_cast<unsigned char>(kmer.back());
    const auto char_in_u = static_cast<unsigned char>(char_in);
    const auto in_mask = kmer::blind_fwd_in_mask(char_in_u, k, masks.rev_in);
    const auto out_mask = kmer::blind_rev_in_mask(char_out_u, k, masks.rev_in);

    const auto fwd = kmer::prev_forward_hash(fwd_hash, char_out_u, in_mask);
    const auto rev = kmer::prev_reverse_hash(rev_hash, out_mask, char_in_u);
    internal::extend_hashes(fwd, rev, k, hash_arr);
  }

  /**
   * Get the array of current hash values (length = \p get_hash_num())
   * @return Pointer to the hash array
   */
  const HASH_TYPE* hashes() const { return hash_arr.data(); }

  /**
   * Get the position of last hashed k-mer or the k-mer to be hashed if roll()
   * has never been called on this NtHash object.
   * @return Position of the most recently hashed k-mer's first base-pair
   */
  ssize_t get_pos() const { return pos; }

  /**
   * Get the number of hashes generated per k-mer.
   * @return Number of hashes per k-mer
   */
  unsigned get_hash_num() const { return hash_arr.size(); }

  /**
   * Get the length of the k-mers.
   * @return \p k
   */
  K_TYPE get_k() const { return static_cast<K_TYPE>(kmer.size()); }

  /**
   * Get the hash value of the forward strand.
   * @return Forward hash value
   */
  HASH_TYPE get_forward_hash() const { return fwd_hash; }

  /**
   * Get the hash value of the reverse strand.
   * @return Reverse-complement hash value
   */
  HASH_TYPE get_reverse_hash() const { return rev_hash; }

private:
  std::string kmer;
  ssize_t pos;
  HASH_TYPE fwd_hash = 0;
  HASH_TYPE rev_hash = 0;
  StrandMasks masks;
  std::vector<HASH_TYPE> hash_arr;
};

} // namespace nthash::kmer

// --- END FILE: blind.hpp ---
// --- BEGIN FILE: nthash.hpp ---

namespace nthash::kmer {

using internal::HASH_TYPE;
using internal::K_TYPE;

class NtHash
{

public:
  /**
   * Construct an ntHash object for k-mers.
   * @param seq C-string containing sequence data
   * @param seq_len Length of the sequence
   * @param num_hashes Number of hashes to generate per k-mer
   * @param k K-mer size
   * @param pos Position in the sequence to start hashing from
   */
  NtHash(const char* seq,
         size_t seq_len,
         unsigned num_hashes,
         K_TYPE k,
         size_t pos = 0)
    : seq(seq, seq_len)
    , k(k)
    , pos(pos)
    , initialized(false)
    , masks(k)
    , hash_arr(num_hashes)
    , k_mult(static_cast<HASH_TYPE>(k) * internal::MULTISEED)
  {
    if (k == 0) {
      throw std::invalid_argument("NtHash: k must be greater than 0");
    }
    if (this->seq.size() < k) {
      std::ostringstream err;
      err << "NtHash: sequence length (" << this->seq.size() << ") ";
      err << "is smaller than k (" << k << ")";
      throw std::invalid_argument(err.str());
    }
    if (pos > this->seq.size() - k) {
      std::ostringstream err;
      err << "NtHash: passed position (" << pos << ") ";
      err << "is larger than sequence length (" << this->seq.size() << ")";
      throw std::invalid_argument(err.str());
    }
  }

  /**
   * Construct an ntHash object for k-mers.
   * @param seq Sequence string
   * @param num_hashes Number of hashes to produce per k-mer
   * @param k K-mer size
   * @param pos Position in sequence to start hashing from
   */
  NtHash(std::string_view seq, unsigned num_hashes, K_TYPE k, size_t pos = 0)
    : NtHash(seq.data(), seq.size(), num_hashes, k, pos)
  {
  }

  /**
   * Calculate the hash values of current k-mer and advance to the next k-mer.
   * NtHash advances one nucleotide at a time until it finds a k-mer with valid
   * characters (ACGTU) and skips over those with invalid characters (non-ACGTU,
   * including N). This method must be called before hashes() is accessed, for
   * the first and every subsequent hashed kmer. get_pos() may be called at any
   * time to obtain the position of last hashed k-mer or the k-mer to be hashed
   * if roll() has never been called on this NtHash object. It is important to
   * note that the number of roll() calls is NOT necessarily equal to get_pos(),
   * if there are N's or invalid characters in the hashed sequence.
   * @return \p true on success and \p false otherwise
   */
  bool roll()
  {
    if (!initialized) {
      return init();
    }
    if (pos >= seq.size() - k) {
      return false;
    }
    const auto char_in = static_cast<unsigned char>(seq[pos + k]);
    if (internal::SEED_TAB[char_in] == internal::SEED_N) {
      pos += k;
      return init();
    }
    const auto char_out = static_cast<unsigned char>(seq[pos]);
    const auto mask_out = masks.fwd_out[internal::CONVERT_TAB[char_out]];
    fwd_hash = kmer::next_forward_hash(fwd_hash, mask_out, char_in);
    const auto mask_in = masks.rev_in[internal::CONVERT_TAB[char_in]];
    rev_hash = kmer::next_reverse_hash(rev_hash, char_out, mask_in);
    internal::extend_hashes(fwd_hash, rev_hash, k_mult, hash_arr);
    ++pos;
    return true;
  }

  /**
   * Like the roll() function, but advance backwards.
   * @return \p true on success and \p false otherwise
   */
  bool roll_back()
  {
    if (!initialized) {
      return init();
    }
    if (pos == 0) {
      return false;
    }
    const auto char_in = static_cast<unsigned char>(seq[pos - 1]);
    if (internal::SEED_TAB[char_in] == internal::SEED_N) {
      if (pos >= k) {
        pos -= k;
        return init();
      }
      return false;
    }
    const auto char_out = static_cast<unsigned char>(seq[pos + k - 1]);
    const auto mask_in = masks.rev_in[3 - internal::CONVERT_TAB[char_in]];
    fwd_hash = kmer::prev_forward_hash(fwd_hash, char_out, mask_in);
    const auto mask_out = masks.rev_in[internal::CONVERT_TAB[char_out]];
    rev_hash = kmer::prev_reverse_hash(rev_hash, mask_out, char_in);
    internal::extend_hashes(fwd_hash, rev_hash, k, hash_arr);
    --pos;
    return true;
  }

  /**
   * Peeks the hash values as if roll() was called (without advancing the
   * NtHash object. The peeked hash values can be obtained through the
   * hashes() method.
   * @return \p true on success and \p false otherwise
   */
  bool peek()
  {
    if (pos >= seq.size() - k) {
      return false;
    }
    return peek(seq[pos + k]);
  }

  /**
   * Like peek(), but as if roll_back() was called.
   * @return \p true on success and \p false otherwise
   */
  bool peek_back()
  {
    if (pos == 0) {
      return false;
    }
    return peek_back(seq[pos - 1]);
  }

  /**
   * Peeks the hash values as if roll() was called for char_in (without
   * advancing the NtHash object. The peeked hash values can be obtained through
   * the hashes() method.
   * @return \p true on success and \p false otherwise
   */
  bool peek(char char_in)
  {
    if (!initialized && !init()) {
      return false;
    }
    const auto char_in_u = static_cast<unsigned char>(char_in);
    if (internal::SEED_TAB[char_in_u] == internal::SEED_N) {
      return false;
    }
    const auto char_out = static_cast<unsigned char>(seq[pos]);
    const auto mask_out = masks.fwd_out[internal::CONVERT_TAB[char_out]];
    const auto fwd = kmer::next_forward_hash(fwd_hash, mask_out, char_in_u);
    const auto mask_in = masks.rev_in[internal::CONVERT_TAB[char_in_u]];
    const auto rev = kmer::next_reverse_hash(rev_hash, char_out, mask_in);
    internal::extend_hashes(fwd, rev, k, hash_arr);
    return true;
  }

  /**
   * Like peek(), but as if roll_back on char_in was called.
   * @return \p true on success and \p false otherwise
   */
  bool peek_back(char char_in)
  {
    if (!initialized && !init()) {
      return false;
    }
    const auto char_in_u = static_cast<unsigned char>(char_in);
    if (internal::SEED_TAB[char_in_u] == internal::SEED_N) {
      return false;
    }
    const auto char_out = static_cast<unsigned char>(seq[pos + k - 1]);
    const auto mask_in = masks.rev_in[3 - internal::CONVERT_TAB[char_in_u]];
    const auto fwd = kmer::prev_forward_hash(fwd_hash, char_out, mask_in);
    const auto mask_out = masks.rev_in[internal::CONVERT_TAB[char_out]];
    const auto rev = kmer::prev_reverse_hash(rev_hash, mask_out, char_in_u);
    internal::extend_hashes(fwd, rev, k, hash_arr);
    return true;
  }

  /**
   * Get the array of current canonical hash values (length = \p get_hash_num())
   * @return Pointer to the hash array
   */
  [[nodiscard]] const HASH_TYPE* hashes() const noexcept
  {
    return hash_arr.data();
  }

  /**
   * Get the position of last hashed k-mer or the k-mer to be hashed if roll()
   * has never been called on this NtHash object.
   * @return Position of the most recently hashed k-mer's first base-pair
   */
  [[nodiscard]] size_t get_pos() const noexcept { return pos; }

  /**
   * Get the number of hashes generated per k-mer.
   * @return Number of hashes per k-mer
   */
  [[nodiscard]] unsigned get_hash_num() const noexcept
  {
    return hash_arr.size();
  }

  /**
   * Get the length of the k-mers.
   * @return \p k
   */
  [[nodiscard]] K_TYPE get_k() const noexcept { return k; }

  /**
   * Get the hash value of the forward strand.
   * @return Forward hash value
   */
  [[nodiscard]] HASH_TYPE get_forward_hash() const noexcept { return fwd_hash; }

  /**
   * Get the hash value of the reverse strand.
   * @return Reverse-complement hash value
   */
  [[nodiscard]] HASH_TYPE get_reverse_hash() const noexcept { return rev_hash; }

private:
  std::string_view seq;
  K_TYPE k;
  size_t pos;
  bool initialized;
  HASH_TYPE fwd_hash = 0;
  HASH_TYPE rev_hash = 0;
  kmer::StrandMasks masks;
  std::vector<HASH_TYPE> hash_arr;
  const HASH_TYPE k_mult;

  /**
   * Initialize the internal state of the iterator
   * @return \p true if successful, \p false otherwise
   */
  bool init()
  {
    while (pos <= seq.size() - k) {
      bool valid = true;
      for (size_t i = k; i > 0 && valid; --i) {
        const auto c = static_cast<unsigned char>(seq[pos + i - 1]);
        if (internal::SEED_TAB[c] == internal::SEED_N) {
          pos += i;
          valid = false;
        }
      }
      if (valid) {
        fwd_hash = kmer::base_forward_hash(seq.data() + pos, k);
        rev_hash = kmer::base_reverse_hash(seq.data() + pos, k);
        internal::extend_hashes(fwd_hash, rev_hash, k_mult, hash_arr);
        initialized = true;
        return true;
      }
    }
    return false;
  }
};

} // namespace nthash::kmer

// --- END FILE: nthash.hpp ---
// --- BEGIN FILE: utils.hpp ---

namespace nthash::seed {

using internal::HASH_TYPE;
using internal::K_TYPE;

using SpacedSeedBlocks = std::vector<std::array<unsigned, 2>>;
using SpacedSeedMonomers = std::vector<unsigned>;

constexpr HASH_TYPE BASE_SEEDS[4] = { internal::SEED_A,
                                      internal::SEED_C,
                                      internal::SEED_G,
                                      internal::SEED_T };

inline void
get_blocks(const std::vector<std::string>& seed_strings,
           std::vector<SpacedSeedBlocks>& blocks,
           std::vector<SpacedSeedMonomers>& monomers)
{
  blocks.clear();
  monomers.clear();
  blocks.reserve(seed_strings.size());
  monomers.reserve(seed_strings.size());

  for (const auto& seed_string : seed_strings) {
    const char pad = seed_string.back() == '1' ? '0' : '1';
    const std::string padded_string = seed_string + pad;
    SpacedSeedBlocks care_blocks;
    SpacedSeedBlocks ignore_blocks;
    std::vector<unsigned> care_monos;
    std::vector<unsigned> ignore_monos;

    unsigned i_start = 0;
    bool is_care_block = padded_string[0] == '1';
    for (unsigned pos = 0; pos < padded_string.length(); pos++) {
      if (is_care_block && padded_string[pos] == '0') {
        if (pos - i_start == 1) {
          care_monos.push_back(i_start);
        } else {
          care_blocks.push_back({ i_start, pos });
        }
        i_start = pos;
        is_care_block = false;
      } else if (!is_care_block && padded_string[pos] == '1') {
        if (pos - i_start == 1) {
          ignore_monos.push_back(i_start);
        } else {
          ignore_blocks.push_back({ i_start, pos });
        }
        i_start = pos;
        is_care_block = true;
      }
    }

    const unsigned num_cares = care_blocks.size() * 2 + care_monos.size();
    const unsigned num_ignores =
      ignore_blocks.size() * 2 + ignore_monos.size() + 2;

    if (num_ignores < num_cares) {
      ignore_blocks.push_back(
        { 0, static_cast<unsigned>(seed_string.length()) });
      blocks.push_back(ignore_blocks);
      monomers.push_back(ignore_monos);
    } else {
      blocks.push_back(care_blocks);
      monomers.push_back(care_monos);
    }
  }
}

inline void
parsed_seeds_to_blocks(const std::vector<std::vector<unsigned>>& seeds,
                       K_TYPE k,
                       std::vector<SpacedSeedBlocks>& blocks,
                       std::vector<SpacedSeedMonomers>& monomers)
{
  std::vector<std::string> seed_strings;
  seed_strings.reserve(seeds.size());

  for (const auto& seed : seeds) {
    std::string seed_string(k, '1');
    for (const auto i : seed) {
      if (i >= k) {
        throw std::invalid_argument(
          "SeedNtHash: parsed seed index out of range");
      }
      seed_string[i] = '0';
    }
    seed_strings.push_back(std::move(seed_string));
  }

  get_blocks(seed_strings, blocks, monomers);
}

inline void
check_seeds(const std::vector<std::string>& seeds, K_TYPE k)
{
  for (const auto& seed : seeds) {
    if (seed.length() != k) {
      throw std::invalid_argument("SeedNtHash: spaced seed string length (" +
                                  std::to_string(seed.length()) +
                                  ") not equal to k=" + std::to_string(k) +
                                  " in " + seed);
    }
  }
}

inline bool
ntmsm64_init(const char* kmer_seq,
             const std::vector<SpacedSeedBlocks>& seeds_blocks,
             const std::vector<SpacedSeedMonomers>& seeds_monomers,
             K_TYPE k,
             unsigned m,
             unsigned m2,
             const std::vector<std::array<HASH_TYPE, 4>>& fwd_shift_table,
             const std::vector<std::array<HASH_TYPE, 4>>& rev_shift_table,
             HASH_TYPE* fh_nomonos,
             HASH_TYPE* rh_nomonos,
             HASH_TYPE* fh_val,
             HASH_TYPE* rh_val,
             HASH_TYPE* h_val)
{
  for (unsigned i_seed = 0; i_seed < m; i_seed++) {
    HASH_TYPE fh_seed = 0;
    HASH_TYPE rh_seed = 0;

    for (const auto& block : seeds_blocks[i_seed]) {
      for (unsigned pos = block[0]; pos < block[1]; pos++) {
        const auto c = static_cast<unsigned char>(kmer_seq[pos]);
        const auto idx = internal::CONVERT_TAB[c];
        fh_seed ^= fwd_shift_table[k - 1 - pos][idx];
        rh_seed ^= rev_shift_table[pos][idx];
      }
    }

    fh_nomonos[i_seed] = fh_seed;
    rh_nomonos[i_seed] = rh_seed;

    for (const auto pos : seeds_monomers[i_seed]) {
      const auto c = static_cast<unsigned char>(kmer_seq[pos]);
      const auto idx = internal::CONVERT_TAB[c];
      fh_seed ^= fwd_shift_table[k - 1 - pos][idx];
      rh_seed ^= rev_shift_table[pos][idx];
    }

    fh_val[i_seed] = fh_seed;
    rh_val[i_seed] = rh_seed;

    const auto base = i_seed * m2;
    h_val[base] = internal::canonical(fh_seed, rh_seed);
    for (unsigned i_hash = 1; i_hash < m2; i_hash++) {
      auto t = h_val[base] *
               (i_hash ^ static_cast<HASH_TYPE>(k) * internal::MULTISEED);
      t ^= t >> internal::MULTISHIFT;
      h_val[base + i_hash] = t;
    }
  }

  return true;
}

template<typename CharAt>
inline void
ntmsm64_forward_core(
  CharAt char_at,
  const std::vector<SpacedSeedBlocks>& seeds_blocks,
  const std::vector<SpacedSeedMonomers>& seeds_monomers,
  K_TYPE k,
  unsigned m,
  unsigned m2,
  const std::vector<std::array<HASH_TYPE, 4>>& fwd_shift_table,
  const std::vector<std::array<HASH_TYPE, 4>>& rev_shift_table,
  HASH_TYPE* fh_nomonos,
  HASH_TYPE* rh_nomonos,
  HASH_TYPE* fh_val,
  HASH_TYPE* rh_val,
  HASH_TYPE* h_val)
{
  for (unsigned i_seed = 0; i_seed < m; i_seed++) {
    HASH_TYPE fh_seed = internal::roll_next(fh_nomonos[i_seed]);
    HASH_TYPE rh_seed = rh_nomonos[i_seed];

    for (const auto& block : seeds_blocks[i_seed]) {
      const auto i_in = block[1];
      const auto i_out = block[0];
      const auto char_in = char_at(i_in);
      const auto char_out = char_at(i_out);

      const auto idx_in = internal::CONVERT_TAB[char_in];
      const auto idx_out = internal::CONVERT_TAB[char_out];

      fh_seed ^= fwd_shift_table[k - i_out][idx_out];
      fh_seed ^= fwd_shift_table[k - i_in][idx_in];
      rh_seed ^= rev_shift_table[i_out][idx_out];
      rh_seed ^= rev_shift_table[i_in][idx_in];
    }

    rh_seed = internal::roll_back(rh_seed);
    fh_nomonos[i_seed] = fh_seed;
    rh_nomonos[i_seed] = rh_seed;

    for (const auto pos : seeds_monomers[i_seed]) {
      const auto c = char_at(pos + 1);
      const auto idx = internal::CONVERT_TAB[c];
      fh_seed ^= fwd_shift_table[k - 1 - pos][idx];
      rh_seed ^= rev_shift_table[pos][idx];
    }

    fh_val[i_seed] = fh_seed;
    rh_val[i_seed] = rh_seed;

    const auto base = i_seed * m2;
    h_val[base] = internal::canonical(fh_seed, rh_seed);
    for (unsigned i_hash = 1; i_hash < m2; i_hash++) {
      auto t = h_val[base] *
               (i_hash ^ static_cast<HASH_TYPE>(k) * internal::MULTISEED);
      t ^= t >> internal::MULTISHIFT;
      h_val[base + i_hash] = t;
    }
  }
}

template<typename CharAt>
inline void
ntmsm64_backward_core(
  CharAt char_at,
  const std::vector<SpacedSeedBlocks>& seeds_blocks,
  const std::vector<SpacedSeedMonomers>& seeds_monomers,
  K_TYPE k,
  unsigned m,
  unsigned m2,
  const std::vector<std::array<HASH_TYPE, 4>>& fwd_shift_table,
  const std::vector<std::array<HASH_TYPE, 4>>& rev_shift_table,
  HASH_TYPE* fh_nomonos,
  HASH_TYPE* rh_nomonos,
  HASH_TYPE* fh_val,
  HASH_TYPE* rh_val,
  HASH_TYPE* h_val)
{
  for (unsigned i_seed = 0; i_seed < m; i_seed++) {
    HASH_TYPE fh_seed = fh_nomonos[i_seed];
    HASH_TYPE rh_seed = internal::roll_next(rh_nomonos[i_seed]);

    for (const auto& block : seeds_blocks[i_seed]) {
      const auto i_in = block[0];
      const auto i_out = block[1];
      const auto char_in = char_at(i_in);
      const auto char_out = char_at(i_out);

      const auto idx_in = internal::CONVERT_TAB[char_in];
      const auto idx_out = internal::CONVERT_TAB[char_out];

      fh_seed ^= fwd_shift_table[k - i_out][idx_out];
      fh_seed ^= fwd_shift_table[k - i_in][idx_in];
      rh_seed ^= rev_shift_table[i_out][idx_out];
      rh_seed ^= rev_shift_table[i_in][idx_in];
    }

    fh_seed = internal::roll_back(fh_seed);
    fh_nomonos[i_seed] = fh_seed;
    rh_nomonos[i_seed] = rh_seed;

    for (const auto pos : seeds_monomers[i_seed]) {
      const auto c = char_at(pos); // Fixed backward monomer index offset
      const auto idx = internal::CONVERT_TAB[c];
      fh_seed ^= fwd_shift_table[k - 1 - pos][idx];
      rh_seed ^= rev_shift_table[pos][idx];
    }

    fh_val[i_seed] = fh_seed;
    rh_val[i_seed] = rh_seed;

    const auto base = i_seed * m2;
    h_val[base] = internal::canonical(fh_seed, rh_seed);
    for (unsigned i_hash = 1; i_hash < m2; i_hash++) {
      auto t = h_val[base] *
               (i_hash ^ static_cast<HASH_TYPE>(k) * internal::MULTISEED);
      t ^= t >> internal::MULTISHIFT;
      h_val[base + i_hash] = t;
    }
  }
}

inline std::vector<std::vector<unsigned>>
parse_seeds(const std::vector<std::string>& seed_strings)
{
  std::vector<std::vector<unsigned>> seed_set;
  seed_set.reserve(seed_strings.size());

  for (const auto& seed_string : seed_strings) {
    std::vector<unsigned> seed;
    for (size_t pos = 0; pos < seed_string.size(); ++pos) {
      if (seed_string[pos] != '1') {
        seed.push_back(static_cast<unsigned>(pos));
      }
    }
    seed_set.push_back(std::move(seed));
  }

  return seed_set;
}

/**
 * Check the current k-mer for non ACGTU's
 * @param seq C array containing the sequence's characters
 * @param k k-mer size
 * @return `true` if any of the first k characters is not an ACGTU, `false`
 * otherwise
 */
[[nodiscard]] inline bool
is_invalid_kmer(const char* seq, unsigned k, size_t& pos_n)
{
  for (size_t i = k; i-- > 0;) {
    if (internal::SEED_TAB[(unsigned char)seq[i]] == internal::SEED_N) {
      pos_n = i;
      return true;
    }
  }
  return false;
}

} // namespace nthash::seed

// --- END FILE: utils.hpp ---
// --- BEGIN FILE: blind.hpp ---

namespace nthash::seed {

class BlindSeedNtHash
{
public:
  /**
   * Construct a BlindSeedNtHash object for spaced seeds on-the-fly.
   */
  BlindSeedNtHash(const char* seq_ptr,
                  const std::vector<std::string>& seeds,
                  unsigned num_hashes_per_seed,
                  K_TYPE k,
                  ssize_t pos = 0)
    : seq(seq_ptr + pos, seq_ptr + pos + k)
    , num_hashes_per_seed(num_hashes_per_seed)
    , k(k)
    , pos(pos)
    , fwd_hash_nomonos(new HASH_TYPE[seeds.size()])
    , rev_hash_nomonos(new HASH_TYPE[seeds.size()])
    , fwd_hash(new HASH_TYPE[seeds.size()])
    , rev_hash(new HASH_TYPE[seeds.size()])
    , hash_arr(new HASH_TYPE[num_hashes_per_seed * seeds.size()])
  {
    if (k == 0)
      throw std::invalid_argument("BlindSeedNtHash: k must be greater than 0");
    if (seeds.empty())
      throw std::invalid_argument("BlindSeedNtHash: empty seeds");

    size_t pos_n = 0;
    if (seed::is_invalid_kmer(seq_ptr + pos, k, pos_n)) {
      throw std::invalid_argument(
        "BlindSeedNtHash: initial k-mer contains invalid characters");
    }

    seed::check_seeds(seeds, k);
    seed::get_blocks(seeds, blocks, monomers);
    init_shift_tables();

    seed::ntmsm64_init(seq_ptr + pos,
                       blocks,
                       monomers,
                       k,
                       static_cast<unsigned>(blocks.size()),
                       num_hashes_per_seed,
                       fwd_shift_table,
                       rev_shift_table,
                       fwd_hash_nomonos.get(),
                       rev_hash_nomonos.get(),
                       fwd_hash.get(),
                       rev_hash.get(),
                       hash_arr.get());
  }

  BlindSeedNtHash(const char* seq_ptr,
                  const std::vector<std::vector<unsigned>>& seeds,
                  unsigned num_hashes_per_seed,
                  K_TYPE k,
                  ssize_t pos = 0)
    : seq(seq_ptr + pos, seq_ptr + pos + k)
    , num_hashes_per_seed(num_hashes_per_seed)
    , k(k)
    , pos(pos)
    , fwd_hash_nomonos(new HASH_TYPE[seeds.size()])
    , rev_hash_nomonos(new HASH_TYPE[seeds.size()])
    , fwd_hash(new HASH_TYPE[seeds.size()])
    , rev_hash(new HASH_TYPE[seeds.size()])
    , hash_arr(new HASH_TYPE[num_hashes_per_seed * seeds.size()])
  {
    if (k == 0)
      throw std::invalid_argument("BlindSeedNtHash: k must be greater than 0");
    if (seeds.empty())
      throw std::invalid_argument("BlindSeedNtHash: empty seeds");

    size_t pos_n = 0;
    if (seed::is_invalid_kmer(seq_ptr + pos, k, pos_n)) {
      throw std::invalid_argument(
        "BlindSeedNtHash: initial k-mer contains invalid characters");
    }

    seed::parsed_seeds_to_blocks(seeds, k, blocks, monomers);
    init_shift_tables();

    seed::ntmsm64_init(seq_ptr + pos,
                       blocks,
                       monomers,
                       k,
                       static_cast<unsigned>(blocks.size()),
                       num_hashes_per_seed,
                       fwd_shift_table,
                       rev_shift_table,
                       fwd_hash_nomonos.get(),
                       rev_hash_nomonos.get(),
                       fwd_hash.get(),
                       rev_hash.get(),
                       hash_arr.get());
  }

  BlindSeedNtHash(const BlindSeedNtHash& obj)
    : seq(obj.seq)
    , num_hashes_per_seed(obj.num_hashes_per_seed)
    , k(obj.k)
    , pos(obj.pos)
    , blocks(obj.blocks)
    , monomers(obj.monomers)
    , fwd_shift_table(obj.fwd_shift_table)
    , rev_shift_table(obj.rev_shift_table)
    , fwd_hash_nomonos(new HASH_TYPE[obj.blocks.size()])
    , rev_hash_nomonos(new HASH_TYPE[obj.blocks.size()])
    , fwd_hash(new HASH_TYPE[obj.blocks.size()])
    , rev_hash(new HASH_TYPE[obj.blocks.size()])
    , hash_arr(new HASH_TYPE[obj.num_hashes_per_seed * obj.blocks.size()])
  {
    std::memcpy(fwd_hash_nomonos.get(),
                obj.fwd_hash_nomonos.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(rev_hash_nomonos.get(),
                obj.rev_hash_nomonos.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(fwd_hash.get(),
                obj.fwd_hash.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(rev_hash.get(),
                obj.rev_hash.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(hash_arr.get(),
                obj.hash_arr.get(),
                obj.num_hashes_per_seed * obj.blocks.size() *
                  sizeof(HASH_TYPE));
  }

  BlindSeedNtHash(BlindSeedNtHash&&) = default;

  void roll(char char_in)
  {
    seed::ntmsm64_forward_core(
      [this, char_in](unsigned idx) {
        if (idx == k)
          return static_cast<unsigned char>(char_in);
        return static_cast<unsigned char>(seq[idx]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(blocks.size()),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos.get(),
      rev_hash_nomonos.get(),
      fwd_hash.get(),
      rev_hash.get(),
      hash_arr.get());

    seq.pop_front();
    seq.push_back(char_in);
    ++pos;
  }

  void roll_back(char char_in)
  {
    seed::ntmsm64_backward_core(
      [this, char_in](unsigned idx) {
        if (idx == 0)
          return static_cast<unsigned char>(char_in);
        return static_cast<unsigned char>(seq[idx - 1]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(blocks.size()),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos.get(),
      rev_hash_nomonos.get(),
      fwd_hash.get(),
      rev_hash.get(),
      hash_arr.get());

    seq.pop_back();
    seq.push_front(char_in);
    --pos;
  }

  void peek(char char_in)
  {
    const auto n = blocks.size();
    auto fwd_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto fwd_hash_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_cpy = std::make_unique<HASH_TYPE[]>(n);

    std::memcpy(fwd_hash_nomonos_cpy.get(),
                fwd_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));
    std::memcpy(rev_hash_nomonos_cpy.get(),
                rev_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));

    seed::ntmsm64_forward_core(
      [this, char_in](unsigned idx) {
        if (idx == k)
          return static_cast<unsigned char>(char_in);
        return static_cast<unsigned char>(seq[idx]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(n),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos_cpy.get(),
      rev_hash_nomonos_cpy.get(),
      fwd_hash_cpy.get(),
      rev_hash_cpy.get(),
      hash_arr.get());
  }

  void peek_back(char char_in)
  {
    const auto n = blocks.size();
    auto fwd_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto fwd_hash_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_cpy = std::make_unique<HASH_TYPE[]>(n);

    std::memcpy(fwd_hash_nomonos_cpy.get(),
                fwd_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));
    std::memcpy(rev_hash_nomonos_cpy.get(),
                rev_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));

    seed::ntmsm64_backward_core(
      [this, char_in](unsigned idx) {
        if (idx == 0)
          return static_cast<unsigned char>(char_in);
        return static_cast<unsigned char>(seq[idx - 1]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(n),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos_cpy.get(),
      rev_hash_nomonos_cpy.get(),
      fwd_hash_cpy.get(),
      rev_hash_cpy.get(),
      hash_arr.get());
  }

  const HASH_TYPE* hashes() const { return hash_arr.get(); }
  ssize_t get_pos() const { return pos; }
  unsigned get_hash_num() const { return num_hashes_per_seed * blocks.size(); }
  unsigned get_hash_num_per_seed() const { return num_hashes_per_seed; }
  K_TYPE get_k() const { return static_cast<K_TYPE>(seq.size()); }
  const HASH_TYPE* get_forward_hash() const { return fwd_hash.get(); }
  const HASH_TYPE* get_reverse_hash() const { return rev_hash.get(); }

private:
  std::deque<char> seq;
  unsigned num_hashes_per_seed;
  K_TYPE k;
  ssize_t pos;
  std::vector<SpacedSeedBlocks> blocks;
  std::vector<SpacedSeedMonomers> monomers;

  std::vector<std::array<HASH_TYPE, 4>> fwd_shift_table;
  std::vector<std::array<HASH_TYPE, 4>> rev_shift_table;

  std::unique_ptr<HASH_TYPE[]> fwd_hash_nomonos;
  std::unique_ptr<HASH_TYPE[]> rev_hash_nomonos;
  std::unique_ptr<HASH_TYPE[]> fwd_hash;
  std::unique_ptr<HASH_TYPE[]> rev_hash;
  std::unique_ptr<HASH_TYPE[]> hash_arr;

  void init_shift_tables()
  {
    fwd_shift_table.resize(k + 1);
    rev_shift_table.resize(k + 1);
    for (size_t d = 0; d <= k; ++d) {
      for (unsigned i = 0; i < 4; ++i) {
        HASH_TYPE seed_f = seed::BASE_SEEDS[i];
        HASH_TYPE seed_r = seed::BASE_SEEDS[3 - i];
        fwd_shift_table[d][i] = internal::roll_next(seed_f, d);
        rev_shift_table[d][i] = internal::roll_next(seed_r, d);
      }
    }
  }
};

} // namespace nthash::seed

// --- END FILE: blind.hpp ---
// --- BEGIN FILE: seed.hpp ---

namespace nthash::seed {

class SeedNtHash
{
public:
  SeedNtHash(const char* seq,
             size_t seq_len,
             const std::vector<std::string>& seeds,
             unsigned num_hashes_per_seed,
             K_TYPE k,
             size_t pos = 0)
    : seq(seq, seq_len)
    , num_hashes_per_seed(num_hashes_per_seed)
    , k(k)
    , pos(pos)
    , initialized(false)
    , fwd_hash_nomonos(new HASH_TYPE[seeds.size()])
    , rev_hash_nomonos(new HASH_TYPE[seeds.size()])
    , fwd_hash(new HASH_TYPE[seeds.size()])
    , rev_hash(new HASH_TYPE[seeds.size()])
    , hash_arr(new HASH_TYPE[num_hashes_per_seed * seeds.size()])
  {
    if (k == 0)
      throw std::invalid_argument("SeedNtHash: k must be greater than 0");
    if (this->seq.size() < k)
      throw std::invalid_argument("SeedNtHash: sequence smaller than k");
    if (pos > this->seq.size() - k)
      throw std::invalid_argument("SeedNtHash: invalid pos");
    if (seeds.empty())
      throw std::invalid_argument("SeedNtHash: empty seeds");

    seed::check_seeds(seeds, k);
    seed::get_blocks(seeds, blocks, monomers);
    init_shift_tables();
  }

  SeedNtHash(std::string_view seq,
             const std::vector<std::string>& seeds,
             unsigned num_hashes_per_seed,
             K_TYPE k,
             size_t pos = 0)
    : SeedNtHash(seq.data(), seq.size(), seeds, num_hashes_per_seed, k, pos)
  {
  }

  SeedNtHash(const char* seq,
             size_t seq_len,
             const std::vector<std::vector<unsigned>>& seeds,
             unsigned num_hashes_per_seed,
             K_TYPE k,
             size_t pos = 0)
    : seq(seq, seq_len)
    , num_hashes_per_seed(num_hashes_per_seed)
    , k(k)
    , pos(pos)
    , initialized(false)
    , fwd_hash_nomonos(new HASH_TYPE[seeds.size()])
    , rev_hash_nomonos(new HASH_TYPE[seeds.size()])
    , fwd_hash(new HASH_TYPE[seeds.size()])
    , rev_hash(new HASH_TYPE[seeds.size()])
    , hash_arr(new HASH_TYPE[num_hashes_per_seed * seeds.size()])
  {
    if (k == 0)
      throw std::invalid_argument("SeedNtHash: k must be greater than 0");
    if (this->seq.size() < k)
      throw std::invalid_argument("SeedNtHash: sequence smaller than k");
    if (pos > this->seq.size() - k)
      throw std::invalid_argument("SeedNtHash: invalid pos");
    if (seeds.empty())
      throw std::invalid_argument("SeedNtHash: empty seeds");

    seed::parsed_seeds_to_blocks(seeds, k, blocks, monomers);
    init_shift_tables();
  }

  SeedNtHash(std::string_view seq,
             const std::vector<std::vector<unsigned>>& seeds,
             unsigned num_hashes_per_seed,
             K_TYPE k,
             size_t pos = 0)
    : SeedNtHash(seq.data(), seq.size(), seeds, num_hashes_per_seed, k, pos)
  {
  }

  SeedNtHash(const SeedNtHash& obj)
    : seq(obj.seq)
    , num_hashes_per_seed(obj.num_hashes_per_seed)
    , k(obj.k)
    , pos(obj.pos)
    , initialized(obj.initialized)
    , blocks(obj.blocks)
    , monomers(obj.monomers)
    , fwd_shift_table(obj.fwd_shift_table)
    , rev_shift_table(obj.rev_shift_table)
    , fwd_hash_nomonos(new HASH_TYPE[obj.blocks.size()])
    , rev_hash_nomonos(new HASH_TYPE[obj.blocks.size()])
    , fwd_hash(new HASH_TYPE[obj.blocks.size()])
    , rev_hash(new HASH_TYPE[obj.blocks.size()])
    , hash_arr(new HASH_TYPE[obj.num_hashes_per_seed * obj.blocks.size()])
  {
    std::memcpy(fwd_hash_nomonos.get(),
                obj.fwd_hash_nomonos.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(rev_hash_nomonos.get(),
                obj.rev_hash_nomonos.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(fwd_hash.get(),
                obj.fwd_hash.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(rev_hash.get(),
                obj.rev_hash.get(),
                obj.blocks.size() * sizeof(HASH_TYPE));
    std::memcpy(hash_arr.get(),
                obj.hash_arr.get(),
                obj.num_hashes_per_seed * obj.blocks.size() *
                  sizeof(HASH_TYPE));
  }

  SeedNtHash(SeedNtHash&&) = default;

  bool roll()
  {
    if (!initialized)
      return init();
    if (pos >= seq.size() - k)
      return false;

    size_t pos_n = 0;
    if (seed::is_invalid_kmer(seq.data() + pos + 1, k, pos_n)) {
      pos += pos_n + 1;
      return init();
    }

    seed::ntmsm64_forward_core(
      [this](unsigned idx) {
        return static_cast<unsigned char>(seq[pos + idx]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(blocks.size()),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos.get(),
      rev_hash_nomonos.get(),
      fwd_hash.get(),
      rev_hash.get(),
      hash_arr.get());
    ++pos;
    return true;
  }

  bool roll_back()
  {
    if (!initialized)
      return init();
    if (pos == 0)
      return false;

    size_t pos_n = 0;
    if (seed::is_invalid_kmer(seq.data() + pos - 1, k, pos_n)) {
      return false; // Safe exit instead of infinite loop
    }

    seed::ntmsm64_backward_core(
      [this](unsigned idx) {
        return static_cast<unsigned char>(seq[pos - 1 + idx]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(blocks.size()),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos.get(),
      rev_hash_nomonos.get(),
      fwd_hash.get(),
      rev_hash.get(),
      hash_arr.get());
    --pos;
    return true;
  }

  bool peek()
  {
    if (pos >= seq.size() - k)
      return false;
    return peek(seq[pos + k]);
  }

  bool peek(char char_in)
  {
    if (!initialized)
      return init();

    const auto n = blocks.size();
    auto fwd_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto fwd_hash_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_cpy = std::make_unique<HASH_TYPE[]>(n);

    std::memcpy(fwd_hash_nomonos_cpy.get(),
                fwd_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));
    std::memcpy(rev_hash_nomonos_cpy.get(),
                rev_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));

    seed::ntmsm64_forward_core(
      [this, char_in](unsigned idx) {
        if (idx == k)
          return static_cast<unsigned char>(char_in);
        return static_cast<unsigned char>(seq[pos + idx]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(n),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos_cpy.get(),
      rev_hash_nomonos_cpy.get(),
      fwd_hash_cpy.get(),
      rev_hash_cpy.get(),
      hash_arr.get());
    return true;
  }

  bool peek_back()
  {
    if (pos == 0)
      return false;
    return peek_back(seq[pos - 1]);
  }

  bool peek_back(char char_in)
  {
    if (!initialized)
      return init();

    const auto n = blocks.size();
    auto fwd_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_nomonos_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto fwd_hash_cpy = std::make_unique<HASH_TYPE[]>(n);
    auto rev_hash_cpy = std::make_unique<HASH_TYPE[]>(n);

    std::memcpy(fwd_hash_nomonos_cpy.get(),
                fwd_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));
    std::memcpy(rev_hash_nomonos_cpy.get(),
                rev_hash_nomonos.get(),
                n * sizeof(HASH_TYPE));

    seed::ntmsm64_backward_core(
      [this, char_in](unsigned idx) {
        if (idx == 0)
          return static_cast<unsigned char>(char_in);
        return static_cast<unsigned char>(seq[pos - 1 + idx]);
      },
      blocks,
      monomers,
      k,
      static_cast<unsigned>(n),
      num_hashes_per_seed,
      fwd_shift_table,
      rev_shift_table,
      fwd_hash_nomonos_cpy.get(),
      rev_hash_nomonos_cpy.get(),
      fwd_hash_cpy.get(),
      rev_hash_cpy.get(),
      hash_arr.get());
    return true;
  }

  const HASH_TYPE* hashes() const { return hash_arr.get(); }
  size_t get_pos() const { return pos; }
  unsigned get_hash_num() const { return num_hashes_per_seed * blocks.size(); }
  unsigned get_hash_num_per_seed() const { return num_hashes_per_seed; }
  K_TYPE get_k() const { return k; }
  const HASH_TYPE* get_forward_hash() const { return fwd_hash.get(); }
  const HASH_TYPE* get_reverse_hash() const { return rev_hash.get(); }

private:
  std::string_view seq;
  unsigned num_hashes_per_seed;
  K_TYPE k;
  size_t pos;
  bool initialized;
  std::vector<SpacedSeedBlocks> blocks;
  std::vector<SpacedSeedMonomers> monomers;

  // O(1) Precomputed shift tables: [rotation_distance][base_index (0-3)]
  std::vector<std::array<HASH_TYPE, 4>> fwd_shift_table;
  std::vector<std::array<HASH_TYPE, 4>> rev_shift_table;

  std::unique_ptr<HASH_TYPE[]> fwd_hash_nomonos;
  std::unique_ptr<HASH_TYPE[]> rev_hash_nomonos;
  std::unique_ptr<HASH_TYPE[]> fwd_hash;
  std::unique_ptr<HASH_TYPE[]> rev_hash;
  std::unique_ptr<HASH_TYPE[]> hash_arr;

  void init_shift_tables()
  {
    fwd_shift_table.resize(k + 1);
    rev_shift_table.resize(k + 1);
    for (size_t d = 0; d <= k; ++d) {
      for (unsigned i = 0; i < 4; ++i) {
        HASH_TYPE seed_f = seed::BASE_SEEDS[i];
        HASH_TYPE seed_r = seed::BASE_SEEDS[3 - i]; // RC mapping
        fwd_shift_table[d][i] = internal::roll_next(seed_f, d);
        rev_shift_table[d][i] = internal::roll_next(seed_r, d);
      }
    }
  }

  bool init()
  {
    size_t pos_n = 0;
    while (pos <= seq.size() - k) {
      if (seed::is_invalid_kmer(seq.data() + pos, k, pos_n)) {
        pos += pos_n + 1;
        continue;
      }
      seed::ntmsm64_init(seq.data() + pos,
                         blocks,
                         monomers,
                         k,
                         static_cast<unsigned>(blocks.size()),
                         num_hashes_per_seed,
                         fwd_shift_table,
                         rev_shift_table,
                         fwd_hash_nomonos.get(),
                         rev_hash_nomonos.get(),
                         fwd_hash.get(),
                         rev_hash.get(),
                         hash_arr.get());
      initialized = true;
      return true;
    }
    return false;
  }
};

} // namespace nthash::seed

// --- END FILE: seed.hpp ---
// --- BEGIN FILE: nthash.hpp ---

namespace nthash {

/**
 * String representing the hash function's name. Only change if hash outputs
 * are different from the previous version. Useful for tracking differences in
 * saved hashes, e.g., in Bloom filters.
 */
inline constexpr std::string_view NTHASH_FN_NAME = "ntHash_v2.5";

static_assert(std::numeric_limits<uint64_t>::max() + 1 == 0,
              "Integers don't overflow on this platform which is necessary for "
              "ntHash canonical hash computation.");

// Expose core classes
using kmer::BlindNtHash;
using kmer::NtHash;
using seed::BlindSeedNtHash;
using seed::SeedNtHash;

} // namespace nthash

// --- END FILE: nthash.hpp ---
