#!/usr/bin/env python3
import collections
import glob
import itertools
import os
import pathlib
import re
import sys
import typing


def get_input_files(paths: typing.Sequence[str]) -> list[pathlib.Path]:
    globs = itertools.chain.from_iterable(glob.glob(p, recursive=True) for p in paths)
    globs = filter(lambda p: p.endswith(".hpp"), globs)
    return sorted({pathlib.Path(p).resolve() for p in set(globs)})


def sort_dependencies(paths: typing.Sequence[pathlib.Path]) -> list[str]:
    inc_re = re.compile(r'^([ \t]*#[ \t]*include[ \t]*["<](.+?)[">].*)', re.MULTILINE)
    pragma_re = re.compile(r"^[ \t]*#[ \t]*pragma[ \t]+once.*$", re.MULTILINE)
    graph = collections.defaultdict(set)
    in_degree = {f: 0 for f in paths}
    external_includes = set()
    file_contents = {}
    paths_set = set(paths)
    for path in sorted(paths):
        contents = path.read_text(encoding="utf-8")
        includes = inc_re.findall(contents)
        local_deps = set()
        for line, inc in includes:
            line = line.strip()
            resolved_inc = (path.parent / inc).resolve()
            if resolved_inc in paths_set:
                local_deps.add(resolved_inc)
            else:
                external_includes.add(line)
        local_deps -= {path}
        in_degree[path] = len(local_deps)
        for dep in local_deps:
            graph[dep].add(path)
        clean = inc_re.sub("", pragma_re.sub("", contents))
        file_contents[path] = re.sub(r"\n{3,}", "\n\n", clean).strip()
    queue = sorted([p for p, deg in in_degree.items() if deg == 0])
    ordered_files = []
    while queue:
        node = queue.pop(0)
        ordered_files.append(node)
        for neighbor in graph[node]:
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                queue.append(neighbor)
        queue.sort()
    if len(ordered_files) != len(paths):
        raise RuntimeError("Cyclic dependency detected among the headers!")
    result = [
        "// ===================================================================",
        "// Amalgamated Header (Auto-generated by scripts/amalgamate.py)",
        "// ===================================================================",
        "#pragma once",
        os.linesep,
    ]
    result.extend(sorted(external_includes))
    result.append(os.linesep)
    for f in ordered_files:
        try:
            rel_name = f.relative_to(pathlib.Path.cwd()).as_posix()
        except ValueError:
            rel_name = f.name
        result.append(f"// --- BEGIN FILE: {rel_name} ---")
        result.append(os.linesep)
        result.append(file_contents[f])
        result.append(os.linesep)
        result.append(f"// --- END FILE: {rel_name} ---")
    return result


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python amalgamate.py <files or globs...>", file=sys.stderr)
        raise SystemExit(1)
    input_headers = get_input_files(sys.argv[1:])
    if len(input_headers) == 0:
        print("No files matched the input patterns.", file=sys.stderr)
        raise SystemExit(1)
    print(*sort_dependencies(input_headers), sep=os.linesep)


if __name__ == "__main__":
    main()
